[package]
name = "todo_list"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[lib]
name = "todo_list"
path = "src/lib.rs"

[[bin]]
name = "todo_list"
path = "src/main.rs"
